### ISSUE TITLE
Cool site!

### ISSUE THREAD

**Issue by bozdoz** [Asjas/Personal-Website#132]
Hey I was trying to send you a greeting on your contact form.  I visited your site from the Cloudflare workers showcase.  I was curious if you were integrating your form with a worker, using Mailgun or equivalent.  Anyway, I like your site; looks like you and I have had similar ideas. My own personal site shares a lot with yours.  Check it out if you'd like: https://github.com/bozdoz/bozdoz.com

You're further ahead of me in terms of a blog, and clearly Gatsby is working great for you for performance.  I thought your favicon was great too. 😄 

Anyway, just wanted to say hi.  Also, If you wanted some help with that contact form, let me know! I've got another project that integrates a Cloudflare worker for use with Mailgun (as I mentioned earlier).

👋

**Comment by Asjas** [comment]
Hey @bozdoz. Thanks! 😄 

I'm actually looking at [Hugo.io](http://gohugo.io/) as a replacement for Gatsby.js. At the moment I've been finding myself maintaining the site and focusing so much on improving the website performance that I've had 0 time to start blogging. So I'm looking at Hugo as a way to create a minimal site (using a theme) that doesn't require a lot of maintenance and hopefully that allows me more time to start blogging more actively. Gatsby is amazing but I kind of fell into procrastination maintenance and I need to get myself out of it. 😆  _Also, I have like 30+ npm packages which is an absolutely pain to maintain_ 😱 

I'll try to get the new website up and running ASAP and then I'll ping you for the Mail integration - I've had a look at doing it myself with Cloudflare Workers but I haven't had much time yet - so that would be great. 😄 I have a Mailjet account so that can be set up to send emails to me.

I also checked out your site 👍. It's a nice and clean design - I like it a lot.

**Comment by bozdoz** [comment]
Looks like I might have to go with Mailjet too (Or sendgrid).  Mailgun just sent an email out discontinuing its free tier.  How timely.
